### PR TITLE
changes to readme

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by askender — CHANGES_REQUESTED** [review]
I think some info shouldd still keep in you personal repo, such as:
application-ulvus-hackfs2020  
test-readme

I think we should discuss about README.md first before we change it.  And you can PR README.md only.

**Comment by ghost** [comment]
i have to learn github. Therefore i close this for now.

**Comment by Shu-Ji** [comment]
What's this?

**Comment by ghost** [comment]
Hi
A team project in hackathon hackfs.com, Anwen, a work in progress. About
ipfs, filecoin, and ethglobal.

About text sharing and publish on ipfs.

How are you  interest?
Have I send something to you?
Ulvus

man. 13. jul. 2020 07.27 skrev Finn <notifications@github.com>:

**Comment by Shu-Ji** [comment]
I  received a notification from github, because  I used to be a member of Anwen.😀

**Comment by ghost** [comment]
Ok. Are you in hackfs? And a team/hacking solo?

Ulvus

tir. 14. jul. 2020 02.34 skrev Finn <notifications@github.com>:

**Pull request closed without merging**
